CREATE DATABASE QuanLyBanAo1;
USE QuanLyBanAo1;

-- Bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    ID_TaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
    TenNguoiDung NVARCHAR(50),
    MatKhau NVARCHAR(50),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100)
);

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    ID_KhachHang INT IDENTITY(1,1) PRIMARY KEY,
    TenKhachHang NVARCHAR(100),
    SoDienThoai VARCHAR(15) UNIQUE,
    DiaChi NVARCHAR(255),
    GioiTinh NVARCHAR(10),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100)
);

-- Bảng THUONGHIEU
CREATE TABLE THUONGHIEU (
    ID_ThuongHieu INT IDENTITY(1,1) PRIMARY KEY,
    TenThuongHieu NVARCHAR(100),
    TrangThai NVARCHAR(20),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100)
);

-- Bảng MAUSAC
CREATE TABLE MAUSAC (
    ID_MauSac INT IDENTITY(1,1) PRIMARY KEY,
    TenMauSac NVARCHAR(50),
    TrangThai NVARCHAR(20),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100)
);

-- Bảng KICHCO
CREATE TABLE KICHCO (
    ID_KichCo INT IDENTITY(1,1) PRIMARY KEY,
    KichCo NVARCHAR(10),
    TrangThai NVARCHAR(20),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100)
);

-- Bảng SANPHAM
CREATE TABLE SANPHAM (
    ID_SanPham INT IDENTITY(1,1) PRIMARY KEY,
    TenSanPham NVARCHAR(100),
    Gia FLOAT,
    SoLuong INT,
    TrangThai NVARCHAR(20),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100)
);

-- Bảng CHITIETSANPHAM
CREATE TABLE CHITIETSANPHAM (
    ID_ChiTietSP INT IDENTITY(1,1) PRIMARY KEY,
    TenSanPham NVARCHAR(100),
    TrangThai NVARCHAR(20),
    HinhAnh NVARCHAR(255),
    ID_SanPham INT,
    ID_ThuongHieu INT,
    ID_MauSac INT,
    ID_KichCo INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_SanPham) REFERENCES SANPHAM(ID_SanPham),
    FOREIGN KEY (ID_ThuongHieu) REFERENCES THUONGHIEU(ID_ThuongHieu),
    FOREIGN KEY (ID_MauSac) REFERENCES MAUSAC(ID_MauSac),
    FOREIGN KEY (ID_KichCo) REFERENCES KICHCO(ID_KichCo)
);

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    ID_NhanVien INT IDENTITY(1,1) PRIMARY KEY,
    TenNhanVien NVARCHAR(100),
    DiaChi NVARCHAR(255),
    SoCCCD VARCHAR(20) UNIQUE,
	VaiTro NVARCHAR(100),
    TrangThai NVARCHAR(20),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100),
    ID_TaiKhoan INT,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TAIKHOAN(ID_TaiKhoan)
);

-- Bảng VOUCHER
CREATE TABLE VOUCHER (
    ID_Voucher INT IDENTITY(1,1) PRIMARY KEY,
    TenVoucher NVARCHAR(100),
    PhanTramGiam FLOAT,
    SoLuong INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100),
    HanSuDung DATETIME,
    TrangThai NVARCHAR(20)
);

-- Bảng HOADON
CREATE TABLE HOADON (
    ID_HoaDon INT IDENTITY(1,1) PRIMARY KEY,
    TenKH NVARCHAR(100),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100),
    TongTien FLOAT,
    TrangThai NVARCHAR(20),
    ID_KhachHang INT,
    ID_NhanVien INT,
    ID_Voucher INT,
    FOREIGN KEY (ID_KhachHang) REFERENCES KHACHHANG(ID_KhachHang),
    FOREIGN KEY (ID_NhanVien) REFERENCES NHANVIEN(ID_NhanVien),
    FOREIGN KEY (ID_Voucher) REFERENCES VOUCHER(ID_Voucher)
);

-- Bảng HOADONCHITIET
CREATE TABLE HOADONCHITIET (
    ID_HoaDonChiTiet INT IDENTITY(1,1) PRIMARY KEY,
    TenSP NVARCHAR(100),
    ThuongHieu NVARCHAR(100),
    MauSac NVARCHAR(50),
    Size NVARCHAR(10),
    SoLuong INT,
    PhanTramGiam FLOAT,
    Gia FLOAT,
    ID_HoaDon INT,
    ID_ChiTietSP INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100),
    FOREIGN KEY (ID_HoaDon) REFERENCES HOADON(ID_HoaDon),
    FOREIGN KEY (ID_ChiTietSP) REFERENCES CHITIETSANPHAM(ID_ChiTietSP)
);

-- Bảng PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    ID_PhieuNhap INT IDENTITY(1,1) PRIMARY KEY,
    NguoiNhap NVARCHAR(100),
    NgayNhap DATETIME DEFAULT CURRENT_TIMESTAMP,
    TongTien FLOAT,
    TrangThai NVARCHAR(20),
    ID_NhanVien INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100),
    FOREIGN KEY (ID_NhanVien) REFERENCES NHANVIEN(ID_NhanVien)
);

-- Bảng CTPHIEUNHAP
CREATE TABLE CTPHIEUNHAP (
    ID_ChiTietPhieuNhap INT IDENTITY(1,1) PRIMARY KEY,
    TenSP NVARCHAR(100),
    Gia FLOAT,
    SoLuongNhap INT,
    ID_PhieuNhap INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    NguoiTao NVARCHAR(100),
    NguoiCapNhat NVARCHAR(100),
    FOREIGN KEY (ID_PhieuNhap) REFERENCES PHIEUNHAP(ID_PhieuNhap)
);

